name: fluttex
description: Easy and fast coding on flutter.
version: 1.0.0
homepage: https://github.com/Amirz64/fluttex.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter: 
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:


